name: Processing
on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      working-dir: ./proc/
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          node-version: 1.14
      - name: Test Cmd
        run: go test ./cmd
        working-directory: ${{env.working-dir}}
      - name: Test Data
        run: go test ./data
        working-directory: ${{env.working-dir}}
      - name: Test Io
        run: go test ./io
        working-directory: ${{env.working-dir}}

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-dir: ./proc/
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          node-version: 1.14
      - run: go build -o proc main.go
        working-directory: ${{env.working-dir}}
